title: My Project Page
description: A landing page to showcase my projects
sitename: Craig's Projects
baseurl: '/project-page'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
